version: '3.8'

services:
  mysql:
    image: mysql
    container_name: test
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: test_redis_container
    ports:
      - "6379:6379"